### ISSUE TITLE
Gem 1.2.0 does not contain fixes for `URI.escape is obsolete`

### ISSUE THREAD

**Issue by rpunt** [duosecurity/duo_api_ruby#33]
The fix for `URI.escape is obsolete` was merged in https://github.com/duosecurity/duo_api_ruby/commit/6a42122f1d141ec073ab3cad4121c13c5b3f737c but no gem version including this fix has been cut. Please cut a current release.

**Comment by AaronAtDuo** [comment]
Done!
https://rubygems.org/gems/duo_api
https://github.com/duosecurity/duo_api_ruby/releases/tag/1.3.0

Thanks for the nudge and thanks for using Duo.

**Comment by rpunt** [comment]
Nice; thank you for the timely response.
