### ISSUE TITLE
Ruby 2.2.3 requires a switch from Digest::HMAC to OpenSSL::HMAC

### ISSUE THREAD

**Issue by nchelluri** [duosecurity/duo_api_ruby#8]
Very similar to this issue in another project: https://github.com/emartech/escher-ruby/issues/5

Basically, Ruby 2.2.3 doesn't have the Digest::HMAC class.

From http://ruby-doc.org//stdlib-1.9.3/libdoc/digest/rdoc/Digest/HMAC.html:

> CAUTION: Use of this library is discouraged, because this implementation was meant to be experimental but somehow got into the 1.9 series without being noticed. Please use OpenSSL::HMAC in the “openssl” library instead.

So we need to switch to using the OpenSSL HMAC class instead.

**Comment by TheKidCoder** [comment]
The gem I maintain has the correct implementation: https://github.com/TheKidCoder/duo-auth
